apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-self-project-backend
  labels:
    app: ai-self-project-backend
    version: v1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-self-project-backend
  template:
    metadata:
      labels:
        app: ai-self-project-backend
        version: v1.0.0
    spec:
      containers:
      - name: backend
        image: ai-self-project-backend:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: GIN_MODE
          value: "release"
        - name: DB_DRIVER
          value: "postgres"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: ai-self-project-config
              key: db_host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: ai-self-project-config
              key: db_port
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: ai-self-project-secrets
              key: db_username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ai-self-project-secrets
              key: db_password
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: ai-self-project-config
              key: db_name
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: ai-self-project-config
              key: redis_host
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: ai-self-project-config
              key: redis_port
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: ai-self-project-secrets
              key: jwt_secret
        - name: TELEMETRY_ENABLED
          value: "true"
        - name: OTLP_ENDPOINT
          value: "http://jaeger-collector:4318/v1/traces"
        - name: ENABLE_TRACING
          value: "true"
        - name: ENABLE_METRICS
          value: "true"
        - name: TELEMETRY_SERVICE_NAME
          value: "ai-self-project-backend"
        - name: TELEMETRY_SERVICE_VERSION
          value: "1.0.0"
        - name: TELEMETRY_ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
