#!/bin/bash

echo "📅 日历多视图功能测试"
echo "======================"

# 检查前端服务是否运行
echo "1. 检查前端服务状态..."
if curl -s http://localhost:5173 > /dev/null; then
    echo "✅ 前端服务运行正常 (http://localhost:5173)"
else
    echo "❌ 前端服务未运行，请先启动: cd frontend && npm run dev"
    exit 1
fi

# 检查后端服务是否运行
echo "2. 检查后端服务状态..."
if curl -s http://localhost:8080/api/v1/health > /dev/null; then
    echo "✅ 后端服务运行正常 (http://localhost:8080)"
else
    echo "❌ 后端服务未运行，请先启动: cd backend && go run main.go"
    exit 1
fi

echo ""
echo "🎯 新增功能总结："
echo "======================"
echo "✅ 日期选择修复："
echo "   - 修复了日期选择偏移问题"
echo "   - 添加了调试日志确保选择正确"
echo "   - 优化了日期处理逻辑"
echo ""
echo "✅ 今天焦点增强："
echo "   - 红色渐变背景突出显示"
echo "   - 添加'今天'标签"
echo "   - 放大效果和阴影"
echo "   - 白色边框增强视觉效果"
echo ""
echo "✅ 多视图支持："
echo "   - 月视图：传统日历布局"
echo "   - 周视图：时间轴布局，显示一周"
echo "   - 日视图：详细时间轴，显示一天"
echo ""
echo "✅ 周视图功能："
echo "   - 7列时间轴布局"
echo "   - 24小时时间段"
echo "   - 点击时间段添加任务"
echo "   - 周末特殊样式"
echo "   - 今天和选中日期高亮"
echo ""
echo "✅ 日视图功能："
echo "   - 24小时详细时间轴"
echo "   - 当前时间高亮显示"
echo "   - 任务时间显示"
echo "   - 点击时间段添加任务"
echo "   - 任务详情展示"
echo ""
echo "✅ 周期TODO时间体现："
echo "   - 深色背景显示优先级"
echo "   - 根据开始和结束时间显示"
echo "   - 不同优先级不同颜色"
echo "   - 悬停效果增强"
echo ""
echo "🌐 访问地址："
echo "   - 前端：http://localhost:5173"
echo "   - 日历页面：http://localhost:5173/dashboard/calendar"
echo ""
echo "📝 测试步骤："
echo "1. 打开浏览器访问 http://localhost:5173"
echo "2. 登录后进入日历管理"
echo "3. 测试月视图："
echo "   - 点击日期选择（应该选择正确日期）"
echo "   - 查看今天的突出显示效果"
echo "   - 双击日期添加任务"
echo "4. 切换到周视图："
echo "   - 查看一周的时间轴布局"
echo "   - 点击时间段添加任务"
echo "   - 查看周末特殊样式"
echo "5. 切换到日视图："
echo "   - 查看24小时详细时间轴"
echo "   - 查看当前时间高亮"
echo "   - 点击时间段添加任务"
echo "6. 验证周期TODO："
echo "   - 创建不同优先级的任务"
echo "   - 查看深色背景显示"
echo "   - 验证时间范围显示"
echo ""
echo "🎨 视觉改进："
echo "======================"
echo "🔴 今天焦点："
echo "   - 红色渐变背景 (#ff6b6b → #ee5a24)"
echo "   - 白色边框和阴影"
echo "   - 放大效果 (scale 1.05)"
echo "   - '今天'标签"
echo ""
echo "📊 多视图布局："
echo "   - 月视图：网格布局"
echo "   - 周视图：时间轴 + 7列"
echo "   - 日视图：垂直时间轴"
echo ""
echo "🎯 优先级显示："
echo "   - 紧急：深红色背景"
echo "   - 高：深橙色背景"
echo "   - 中：深蓝色背景"
echo "   - 低：深绿色背景"
echo ""
echo "✨ 现在日历支持多视图，今天焦点明显，周期TODO时间体现清晰！"
