#!/bin/bash

echo "🎯 日历时间段模式和跨天连接功能验证"
echo "====================================="

# 检查前端服务是否运行
echo "1. 检查前端服务状态..."
if curl -s http://localhost:5173 > /dev/null; then
    echo "✅ 前端服务运行正常 (http://localhost:5173)"
else
    echo "❌ 前端服务未运行，请先启动: cd frontend && npm run dev"
    exit 1
fi

# 检查后端服务是否运行
echo "2. 检查后端服务状态..."
if curl -s http://localhost:8080/api/v1/health > /dev/null; then
    echo "✅ 后端服务运行正常 (http://localhost:8080)"
else
    echo "❌ 后端服务未运行，请先启动: cd backend && go run main.go"
    exit 1
fi

echo ""
echo "🎯 新增功能总结："
echo "===================="
echo "✅ 时间段模式："
echo "   - 支持精确到小时和分钟的时间选择"
echo "   - 提供时间预设按钮（上午、下午、晚上等）"
echo "   - 支持自定义时间段设置"
echo ""
echo "✅ 跨天任务连接："
echo "   - 跨天任务在日历上连续显示"
echo "   - 第一天：左侧圆角，右侧连接线"
echo "   - 中间天：左右连接线，无圆角"
echo "   - 最后天：右侧圆角，左侧连接线"
echo "   - 相同颜色块连接，视觉上形成连续效果"
echo ""
echo "✅ 两种模式支持："
echo "   - 日期模式：全天任务，可选择跨天"
echo "   - 时间段模式：精确时间，单天时间段"
echo ""
echo "🔧 技术实现详情："
echo "===================="
echo "📅 时间预设功能："
echo "   - 上午：09:00-12:00"
echo "   - 下午：14:00-18:00"
echo "   - 晚上：19:00-22:00"
echo "   - 全天：00:00-23:59"
echo "   - 1小时、2小时、4小时预设"
echo ""
echo "🎨 跨天连接样式："
echo "   - 使用CSS伪元素创建连接线"
echo "   - 继承任务颜色，保持视觉一致性"
echo "   - 圆角设计，美观的连接效果"
echo "   - 层级管理，确保正确显示"
echo ""
echo "📝 数据结构增强："
echo "   - isMultiDay：是否为跨天任务"
echo "   - isFirstDay：是否为第一天"
echo "   - isLastDay：是否为最后一天"
echo "   - isMiddleDay：是否为中间天"
echo ""
echo "🌐 访问地址："
echo "   - 前端：http://localhost:5173"
echo "   - 日历页面：http://localhost:5173/dashboard/calendar"
echo ""
echo "📝 测试步骤："
echo "1. 打开浏览器访问 http://localhost:5173"
echo "2. 登录后进入日历管理"
echo "3. 测试时间段模式："
echo "   - 点击任意时间段，选择时间段模式"
echo "   - 测试时间预设按钮功能"
echo "   - 自定义时间段设置"
echo "4. 测试跨天任务："
echo "   - 创建全天任务，选择不同开始和结束日期"
echo "   - 观察跨天任务在日历上的连续显示效果"
echo "   - 验证连接线的视觉效果"
echo "5. 测试两种模式切换："
echo "   - 全天任务模式：选择跨天"
echo "   - 时间段模式：精确时间选择"
echo ""
echo "🎯 预期结果："
echo "===================="
echo "✅ 时间段选择精确到分钟"
echo "✅ 时间预设按钮正常工作"
echo "✅ 跨天任务视觉上连续连接"
echo "✅ 连接线颜色与任务颜色一致"
echo "✅ 两种模式切换流畅"
echo "✅ 表单验证和错误处理正常"
echo ""
echo "✨ 现在日历支持精确时间段和跨天连接，功能更加完善！"
